language: python
python:
  - "2.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-hid-usb-mouse
  - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-libs
  - PLATFORMIO_PROJECT_DIR=examples/mbed-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-dsp
  # - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos
  - PLATFORMIO_PROJECT_DIR=examples/mbed-serial

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: NKEPj9NKaysnsyfWCayez78C0ZOa2hNJ5owl+mDI+s8uDona/9I6U4kx6Pwz1CnSQuTBC2xYTGtuftev+Pn5W+zTyGgGurSKJ7SNgNlNk1ZqLj2230z5v0H3Ml5mEumNpvgJ6rNU/c9zGViHIr9vwWL5umGlN+ChYgE4WHArPNnPVWhOjsfj0WmIJWI/k3j7zhXiLOWXZI81WZUVMBSuOWoiQnhHnzyV3VJKCHKPJCaXzaDPLifEmR2llLwRphN4SJI83J8nzgSCh9neNEFOHPNXZY+5oatw38bt9a547FThHj6Bnv8mDdipfCVnFpI8OQMPaKgJsqmllH8ZMI7pcVn+qvOePYD4aAuUH9f7zeHZCDlNNtR8z1hEfYaTp/vy+sEF/gBCnsK/Z5lWR3AvLLD/h4HlaJjdwlq7GIQ07u22T7T03QIdreE/iUCAIXFkmwJ5ea6DvSOP9jBw6CYhsMxJjDpLywMh4RujfFc/6wjNyYYm5YLjkFYshOqLh3YAoHrUUhOYPyjis7j0eHb7CkYpshbovTqUg+IK6XHtV64Om31SWW2Ad9VZ/Q9uQRHRsP+WL/RmO9uMa9rSaX/fgWe07NaiUTJT5BA85+ndTXUIAim64TP5kDi+iYs3nQiCZrlA/6SPWTBaLyLmNElJE9iIy0yv5W4x8MrJf9TBF8o=
    on_failure: always
    on_success: change
